from dataclasses import dataclass
from typing import List, Optional

@dataclass
class GitConfig:
    """Git 相关配置"""
    
    # 分支配置
    branch_prefix: str = "impl/"  # 实现分支前缀
    base_branch: str = "main"     # 目标分支
    
    # PR 配置
    pr_title_template: str = "AI: Implementation for {test_file}"
    pr_body_template: str = """
    This PR was automatically generated by AI.
    
    Implementation file: `{impl_file}`
    Test file: `{test_file}`
    
    Please review the changes and provide feedback.
    """
    
    # Code Review 配置
    reviewers: List[str] = None  # PR 审查者
    labels: List[str] = None     # PR 标签
    
    # Git 操作配置
    push_to_remote: bool = True  # 是否推送到远程
    delete_branch_after_merge: bool = True  # 合并后是否删除分支 